const {
  NODE_ENV,
  GRAPHQL_API,
  BRANCH,
  GOOGLE_CLIENT_ID,
  FACEBOOK_CLIENT_ID,
  ESLINT_NO_DEV_ERRORS,
  BUILD_NUMBER,
  WS_URL,
  JIRA_API_ID,
  REDIRECT_URI,
} = process.env;

export default {
  NODE_ENV,
  GRAPHQL_API,
  BRANCH,
  GOOGLE_CLIENT_ID,
  FACEBOOK_CLIENT_ID,
  ESLINT_NO_DEV_ERRORS,
  BUILD_NUMBER,
  WS_URL,
  JIRA_API_ID,
  REDIRECT_URI,
};
