export const EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST';

export const WRONG_AUTH_TYPE = 'WRONG_AUTH_TYPE';

export const UNVERIFIED_USER = 'UNVERIFIED_USER';

export const INCORRECT_EMAIL = 'INCORRECT_EMAIL';

export const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';

export const BLOCK_LOGIN = 'BLOCK_LOGIN';

export const UNREGISTERED = 'UNREGISTERED';

export const BLOCK_RESET_PASSWORD = 'BLOCK_RESET_PASSWORD';

export const BLOCK_RESEND_VERIFICATION = 'BLOCK_RESEND_VERIFICATION';

export const EXIST_PASSWORD = 'EXIST_PASSWORD';

export const RESET_PASSWORD_FOR_THIRD_PARTY = 'RESET_PASSWORD_FOR_THIRD_PARTY';
